server:
  port: ${APP_PORT:18080}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5432/task_center}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  thymeleaf:
    cache: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  swagger-ui:
    path: /swagger-ui.html

outbox:
  dispatch:
    fixed-delay-ms: ${OUTBOX_DISPATCH_DELAY_MS:5000}

mattermost:
  base-url: ${MM_BASE_URL:http://localhost:8065}
  bot-token: ${MM_BOT_TOKEN:}
  fallback-bot-token: ${MM_FALLBACK_BOT_TOKEN:}
  alert-channel-id: ${MM_ALERT_CHANNEL_ID:4odsfctn8trymycthdk9qafqjr}
  alert-mentions: ${MM_ALERT_MENTIONS:@bot-leader @admin}
